### ISSUE TITLE
Getting periodic 'Connection not yet open' errors

### ISSUE THREAD

**Issue by eddiebroeder** [intel/machinepack-mssql#8]
I'm using version 1.2.0, and periodically getting the below errors (pretty often, one every 10 or so queries):
```
(node:6196) UnhandledPromiseRejectionWarning: ConnectionError: Connection not yet open.
    at Proxy._acquire (c:\users\user\desktop\web-api\node_modules\machinepack-mssql\node_modules\mssql\lib\base\connection-pool.js:105:36)
    at Proxy.acquire (c:\users\user\desktop\web-api\node_modules\machinepack-mssql\node_modules\mssql\lib\base\connection-pool.js:91:56)
    at Immediate.<anonymous> (c:\users\user\desktop\web-api\node_modules\machinepack-mssql\node_modules\mssql\lib\tedious\request.js:401:19)
    at processImmediate (internal/timers.js:439:21)
(node:6196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 315)
```

Let me know if this is something I should open with tedious instead/also.

**Comment by eddiebroeder** [comment]
@davepreston  I tried running machinepack-mssql with node-mssql@6.1.0 (released yesterday), and this seems to have solved the problem (see tediousjs/node-mssql#988).

There are still error messages, but now they say something like "Connection is closing", and the failures seem to happen right away, instead of before where they seem to take quite a while to actually error out. Since they fail quickly in the new version, my front end can just quickly retry the request and the user experience is much better (as before I couldn't retry until the the request timed out).

I did a little debugging and it looks like the pool is being destroyed after each connection, do you know if this is intentional, or some side effect?

Thanks!

**Comment by eddiebroeder** [comment]
@davepreston Hello, just checking to see if there's any plan to upgrade to node-mssql@6.1.0 in the foreseeable future?

**Comment by davepreston** [comment]
@eddiebroeder yes. I'm looking into it today. Assuming no issues I'll bump and push asap.

**Comment by eddiebroeder** [comment]
@davepreston Sound great, thanks!

**Comment by davepreston** [comment]
merged and pushed to npm. Feel free to re-open if you continue to see issues.
